### ISSUE TITLE
operation timeout

### ISSUE THREAD

**Issue by nocomp** [itcef/CarPwner#1]
hi,
i gave a try, but i had this error when using python2.7:

nocomp@zebox:~/tools/sdr/CarPwner$ sudo python2.7 CarPwner.py -f 433980000 -r 1818 -m -40
Configuring Scanner on Frequency: 433980000
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')
Error in resetup():USBError(110, u'Operation timed out')

any idea what could be wrong?
best regards

**Comment by itcef** [comment]
Hi, ur yard stick one firmware?
